name: grape-vision
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch
  - torchvision
  - numpy
  - shapely
  - tqdm
  - matplotlib
  - pandas
  - opencv
  - scikit-image
  - lap
  - pip
  - pip:
    - ultralytics
