# -----------------------------------------------------------------------------
# Master Configuration for the Grape Vision Pipeline
#
# This file controls all model paths, thresholds, and operational parameters.
# -----------------------------------------------------------------------------

# --- Model Metadata ---
# This section defines data about the models themselves.
model_data:
  # IMPORTANT: List the class names in the EXACT order your model was trained on.
  # Class ID 0 will be the first name, ID 1 the second, and so on.
  class_names: ['Berry', 'Pearl']

# --- Model Paths ---
# Paths to the trained model weight files (.pt).
# These can be absolute paths or relative to the project's root directory.
models:
  # Model used for initial detection of objects.
  detection_weights: "models/yolov11l_detect.pt"
  
  # Model used for precise segmentation of objects (can be same as detection).
  segmentation_weights: "models/YOLOV8L_seg_03-08-23.pt"

# --- Component Settings ---
# Fine-tune the behavior of each component in the pipeline.

detection_settings:
  # Detections with a confidence score below this value will be ignored.
  confidence_threshold: 0.5

segmentation_settings:
  # Confidence threshold for the segmentation model.
  confidence_threshold: 0.4

tracking_settings:
  # Path to the specialized tracker configuration file.
  # This file controls the low-level tracking algorithm (e.g., BoT-SORT, ByteTrack).
  # You can find default versions in the ultralytics library or create your own.
  tracker_config_file: "configs/tracker.yaml"

# --- Analysis & Output Settings ---
# Control the analysis methods and what gets saved.

analysis_settings:
  # The method used to calculate volume from a mask.
  # Available options: 'ransac', 'convex_hull'
  volume_estimation_method: "convex_hull"

  # Settings specific to time-series (video/image sequence) analysis.
  video:
    # If true, the 'track' command will create folders for each tracked
    # berry containing its cropped images over time.
    create_crop_folders: true